using System;
using System.Text.Json.Serialization;

namespace Maib.Ecomm.Api.Connector.Models.Responses;

public sealed class CompleteDmsPaymentResponse
{
    /// <summary>
    /// Transaction identifier assigned by maib ecomm
    /// </summary>
    [JsonPropertyName("payId")]
    public Guid PayId { get; set; }

    /// <summary>
    /// Order ID generated by Merchant website/app
    /// </summary>
    [JsonPropertyName("orderId")]
    public string? OrderId { get; set; }

    /// <summary>
    /// <see href="https://docs.maibmerchants.md/en/transaction-and-3d-secure-status#transaction-status">Transaction status</see>
    /// 
    /// OK - successfully completed.
    /// </summary>
    [JsonPropertyName("status")]
    public string? Status { get; set; }

    /// <summary>
    /// Transaction status code
    /// </summary>
    [JsonPropertyName("statusCode")]
    public string? StatusCode { get; set; }

    /// <summary>
    /// Transaction status information message
    /// </summary>

    [JsonPropertyName("statusMessage")]
    public string? StatusMessage { get; set; }

    /// <summary>
    /// RRN - Transaction ID generated by maib ecomm
    /// </summary>
    [JsonPropertyName("rrn")]
    public string? Rrn { get; set; }

    /// <summary>
    /// Approval Code - The transaction approval code generated by the card issuing bank
    /// </summary>
    [JsonPropertyName("approval")]
    public string? Approval { get; set; }

    /// <summary>
    /// Masked number card
    /// </summary>
    [JsonPropertyName("cardNumber")]
    public string CardNumber { get; set; }

    /// <summary>
    /// Amount debited from Customer's bank account. Format: X.XX
    /// </summary>
    [JsonPropertyName("confirmAmount")]
    public decimal ConfirmAmount { get; set; }
}