using System;
using System.Text.Json.Serialization;

namespace MerchantHub.Connector.Proxy.Api.Models.Responses;

public sealed class InitPaymentResponse
{
    /// <summary>
    /// Transaction identifier assigned by maib ecomm
    /// </summary>
    [JsonPropertyName("payId")]
    public Guid PayId { get; set; }

    /// <summary>
    /// Order ID generated by Merchant website/app
    /// </summary>
    [JsonPropertyName("orderId")]
    public string? OrderId { get; set; }

    /// <summary>
    /// The link to the maib ecomm checkout page where the Customer must be redirected to enter their card details (or pay via Apple Pay/Google Pay)
    /// </summary>
    [JsonPropertyName("payUrl")]
    public string PayUrl { get; set; }
}