using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;
using Maib.Ecomm.Api.Connector.Models.Enums;

namespace Maib.Ecomm.Api.Connector.Models.Requests;

public sealed class ExecuteOneClickPaymentRequest : BaseRequest
{
    protected override string Action => "/v1/execute-oneclick";

    /// <summary>
    /// Card identifier saved in maib ecomm system
    /// </summary>
    [JsonPropertyName("billerId")]
    public Guid BillerId { get; set; }

    /// <summary>
    /// Transaction amount. Format: X.XX
    /// 
    /// E.g: 10.25 (currency=USD) means $10 and 25 cents.
    /// </summary>
    [JsonPropertyName("amount")]
    public decimal Amount { get; set; }

    /// <summary>
    /// Transaction currency (MDL/EUR/USD)
    /// </summary>
    [JsonPropertyName("currency")]
    public Currency Currency { get; set; }

    /// <summary>
    /// Customer IP
    /// </summary>
    [JsonPropertyName("clientIp")]
    public string ClientIp { get; set; }

    /// <summary>
    /// maib ecomm checkout page language
    /// 
    /// Allowed values: ro/en/ru
    /// 
    /// If this parameter is not passed, the page will be displayed in English.
    /// </summary>
    [JsonPropertyName("language")]
    public string? Language { get; set; }

    /// <summary>
    /// Payment description.
    /// 
    /// Displayed on maib ecomm checkout page
    /// </summary>
    [JsonPropertyName("description")]
    public string? Description { get; set; }

    /// <summary>
    ///  Order ID generated by Merchant website/app
    /// </summary>
    [JsonPropertyName("orderId")]
    public string? OrderId { get; set; }

    /// <summary>
    /// Shipping cost
    /// </summary>
    [JsonPropertyName("delivery")]
    public decimal? Delivery { get; set; }

    /// <summary>
    /// The products or services ordered from the website/app
    /// </summary>
    [JsonPropertyName("items")]
    public List<ItemDto>? Items { get; set; }

    /// <summary>
    /// The link where the Merchant will receive the final response with the transaction status and data.
    /// 
    /// If this parameter is not passed, its value will be taken from maibmerchants.
    /// </summary>
    [JsonPropertyName("callbackUrl")]
    public string? CallBackUrl { get; set; }

    /// <summary>
    /// The link where the Customer will be redirected if the transaction was successful.
    /// 
    /// If this parameter is not passed, its value will be taken from maibmerchants.(GET request + payId&amp;orderId&amp;billerId)
    /// </summary>
    [JsonPropertyName("okUrl")]
    public string? OkUrl { get; set; }

    /// <summary>
    /// The link where the Customer will be redirected if the transaction was failed.
    /// 
    /// If this parameter is not passed, its value will be taken from maibmerchants. (GET request + payId&amp;orderId)
    /// </summary>
    [JsonPropertyName("failUrl")]
    public string? FailUrl { get; set; }
}